# Generated by Django 2.1.4 on 2019-01-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('sport', models.CharField(choices=[('badmiton', 'Badmiton'), ('ballbadmiton', 'Ball Badmiton'), ('basketball', 'Basketball'), ('cricket', 'Cricket'), ('chess', 'Chess'), ('football', 'Football'), ('handball', 'Handball'), ('hockey', 'Hockey'), ('kabaddi', 'Kabaddi'), ('khokho', 'Kho-Kho'), ('tabletennis', 'Table Tennois')], max_length=20)),
                ('team1', models.CharField(choices=[('coral', 'Coral'), ('emerald', 'Emerald'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('pearl', 'Peark'), ('sapphire', 'Sapphire')], max_length=10)),
                ('team2', models.CharField(choices=[('coral', 'Coral'), ('emerald', 'Emerald'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('pearl', 'Peark'), ('sapphire', 'Sapphire')], max_length=10)),
                ('team3', models.CharField(choices=[('coral', 'Coral'), ('emerald', 'Emerald'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('pearl', 'Peark'), ('sapphire', 'Sapphire')], max_length=10)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('team3_score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.AlterUniqueTogether(
            name='standings',
            unique_together={('gender', 'sport')},
        ),
    ]
