# Generated by Django 2.1.4 on 2019-02-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'verbose_name_plural': 'Standings'},
        ),
    ]
